((nil . ((indent-tabs-mode . nil)
         (tab-width . 4)
         (fill-column . 100)))
 (c-mode . ((c-file-style . "k&r")
            (c-basic-offset . 4)))
 (makefile-mode . ((indent-tabs-mode . t)))
 (asm-mode . ((indent-tabs-mode . t)))
 (shell-script-mode . ((indent-tabs-mode . t)))
 ((nil . ((truncate-lines . t)))
  (text-mode . ((eval . ((turn-on-auto-fill))))))
 ("LibOS/glibc-2.19"
  . ((nil . ((tab-width . 8)))))
 ("LibOS/shim/src/syscallas.S"
  . ((nil . ((indent-tabs-mode . nil)
             (c-basic-offset . 8)))))
 )
